# Generated by Django 4.2.1 on 2023-06-04 16:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quickstart', '0002_rename_position_employee_role'),
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=50, null=True)),
                ('last_name', models.CharField(max_length=50, null=True)),
                ('age', models.IntegerField(blank=True, null=True)),
                ('residential_area', models.CharField(max_length=50, null=True)),
                ('lab', models.CharField(choices=[('AnitaB Lab', 'AnitaB Lab'), ('Ada Lab', 'Ada Lab'), ('Hopper Lab', 'Hopper Lab')], max_length=254, null=True)),
                ('countries', models.CharField(choices=[('Kenya', 'Kenya'), ('Uganda', 'Uganda'), ('Rwanda', 'Rwanda'), ('Tanzania', 'Tanzania')], max_length=254, null=True)),
            ],
        ),
    ]
